// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace BookManagementSystem.Entity
{
    public partial class BookmanagementsystemContext : DbContext
    {
        public BookmanagementsystemContext()
        {
        }

        public BookmanagementsystemContext(DbContextOptions<BookmanagementsystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AuthorDetails> AuthorDetails { get; set; }
        public virtual DbSet<BookDetails> BookDetails { get; set; }
        public virtual DbSet<Login> Login { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=BookManagementSystem;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<AuthorDetails>(entity =>
            {
                entity.Property(e => e.Authour_Name).IsUnicode(false);

                entity.Property(e => e.Create_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Update_Time_Stamp).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<BookDetails>(entity =>
            {
                entity.HasKey(e => e.BookDetail_Id)
                    .HasName("PK__BookDeta__6397E465DA4B18DC");

                entity.Property(e => e.Book_Title).IsUnicode(false);

                entity.Property(e => e.Create_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Update_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.Author)
                    .WithMany(p => p.BookDetails)
                    .HasForeignKey(d => d.Author_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BookDetails_BookDetails");
            });

            modelBuilder.Entity<Login>(entity =>
            {
                entity.Property(e => e.Create_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.Update_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.User_Name).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}