// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookManagementSystem.Entity
{
    public partial class Login
    {
        [Key]
        public int User_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string User_Name { get; set; }
        [Required]
        [StringLength(16)]
        public string Password { get; set; }
        public bool Is_Delete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Update_Time_Stamp { get; set; }
    }
}